"""
Scheduler for AI Employee

Handles scheduled tasks like:
- Daily briefings (8 AM)
- Weekly CEO briefing (Monday 7 AM)
- Subscription audits (Weekly)
- Accounting sync (Daily)

Silver Tier component.

Usage:
    python scheduler.py ../AI_Employee_Vault
"""

import sys
import time
import logging
import subprocess
from pathlib import Path
from datetime import datetime
from typing import Callable, List
from apscheduler.schedulers.blocking import BlockingScheduler
from apscheduler.triggers.cron import CronTrigger

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)


class AIScheduler:
    """
    Scheduler for AI Employee tasks.
    
    Schedules:
    - Daily briefings
    - Weekly reports
    - Periodic audits
    """
    
    def __init__(self, vault_path: str):
        """
        Initialize the scheduler.
        
        Args:
            vault_path: Path to the Obsidian vault
        """
        self.vault_path = Path(vault_path).resolve()
        self.logger = logging.getLogger('AIScheduler')
        
        # Folders
        self.briefings = self.vault_path / 'Briefings'
        self.logs = self.vault_path / 'Logs'
        self.dashboard = self.vault_path / 'Dashboard.md'
        
        # Ensure folders exist
        self.briefings.mkdir(parents=True, exist_ok=True)
        self.logs.mkdir(parents=True, exist_ok=True)
        
        # Scheduler
        self.scheduler = BlockingScheduler()
        
        self._setup_jobs()
        
        self.logger.info(f'AIScheduler initialized for {self.vault_path}')
    
    def _setup_jobs(self):
        """Set up scheduled jobs."""
        
        # Daily Briefing - 8:00 AM every day
        self.scheduler.add_job(
            self.generate_daily_briefing,
            CronTrigger(hour=8, minute=0),
            id='daily_briefing',
            name='Daily Briefing'
        )
        self.logger.info('Scheduled: Daily Briefing at 8:00 AM')
        
        # Weekly CEO Briefing - Monday 7:00 AM
        self.scheduler.add_job(
            self.generate_ceo_briefing,
            CronTrigger(day_of_week='mon', hour=7, minute=0),
            id='ceo_briefing',
            name='CEO Weekly Briefing'
        )
        self.logger.info('Scheduled: CEO Weekly Briefing on Monday 7:00 AM')
        
        # Subscription Audit - Sunday 10:00 PM
        self.scheduler.add_job(
            self.run_subscription_audit,
            CronTrigger(day_of_week='sun', hour=22, minute=0),
            id='subscription_audit',
            name='Weekly Subscription Audit'
        )
        self.logger.info('Scheduled: Subscription Audit on Sunday 10:00 PM')
        
        # Accounting Sync - Daily 6:00 PM
        self.scheduler.add_job(
            self.sync_accounting,
            CronTrigger(hour=18, minute=0),
            id='accounting_sync',
            name='Daily Accounting Sync'
        )
        self.logger.info('Scheduled: Accounting Sync at 6:00 PM')
    
    def generate_daily_briefing(self):
        """Generate daily briefing."""
        self.logger.info('Generating daily briefing...')
        
        today = datetime.now().strftime('%Y-%m-%d')
        briefing_file = self.briefings / f'{today}_Daily_Briefing.md'
        
        content = f"""---
generated: {datetime.now().isoformat()}
period: {today}
type: daily_briefing
---

# Daily Briefing - {today}

## Summary
*Generated by AI Employee Scheduler*

## Today's Schedule
- Review /Needs_Action folder
- Process pending items
- Update Dashboard

## Reminders
- Check pending approvals
- Review logs for errors

---
*To customize: Edit scheduler.py*
"""
        
        briefing_file.write_text(content, encoding='utf-8')
        self.logger.info(f'Daily briefing created: {briefing_file.name}')
    
    def generate_ceo_briefing(self):
        """Generate weekly CEO briefing."""
        self.logger.info('Generating CEO weekly briefing...')
        
        today = datetime.now().strftime('%Y-%m-%d')
        briefing_file = self.briefings / f'{today}_CEO_Weekly_Briefing.md'
        
        content = f"""---
generated: {datetime.now().isoformat()}
period: Weekly
type: ceo_briefing
---

# CEO Weekly Briefing

## Executive Summary
*Week of {today}*

## Revenue Tracking
- **Monthly Goal:** $10,000
- **Current MTD:** $0 (Update from accounting)
- **Trend:** On track

## Completed Tasks This Week
*Review /Done folder for completed items*

## Bottlenecks Identified
*Items that took longer than expected*

## Proactive Suggestions

### Cost Optimization
*Review subscriptions and recurring expenses*

### Upcoming Deadlines
*List from Business_Goals.md*

## Action Items for This Week
1. Review pending approvals
2. Check subscription usage
3. Process any backlog

---
*Generated by AI Employee - Silver Tier*
"""
        
        briefing_file.write_text(content, encoding='utf-8')
        self.logger.info(f'CEO briefing created: {briefing_file.name}')
    
    def run_subscription_audit(self):
        """Run weekly subscription audit."""
        self.logger.info('Running subscription audit...')
        
        # This would integrate with accounting system
        # For Silver Tier, create a template
        
        today = datetime.now().strftime('%Y-%m-%d')
        audit_file = self.vault_path / 'Accounting' / f'{today}_Subscription_Audit.md'
        
        content = f"""---
generated: {datetime.now().isoformat()}
type: subscription_audit
status: pending_review
---

# Subscription Audit - {today}

## Subscriptions to Review

| Service | Cost | Last Used | Action |
|---------|------|-----------|--------|
| *Add from Business_Goals.md* | - | - | - |

## Recommendations
- Cancel unused subscriptions
- Negotiate better rates
- Consolidate duplicate tools

---
*Review and update manually*
"""
        
        audit_file.parent.mkdir(parents=True, exist_ok=True)
        audit_file.write_text(content, encoding='utf-8')
        self.logger.info(f'Subscription audit created: {audit_file.name}')
    
    def sync_accounting(self):
        """Sync accounting data."""
        self.logger.info('Running accounting sync...')
        
        # This would integrate with accounting API
        # For Silver Tier, create a template
        
        today = datetime.now().strftime('%Y-%m-%d')
        accounting_file = self.vault_path / 'Accounting' / f'{today}_Transactions.md'
        
        content = f"""---
generated: {datetime.now().isoformat()}
type: accounting_sync
status: pending_review
---

# Accounting Sync - {today}

## Transactions Today
*Import from bank/accounting system*

## Categorization
*Auto-categorize transactions*

## Flags
- Transactions over $100 need review
- New payees need approval

---
*Review and update manually*
"""
        
        accounting_file.parent.mkdir(parents=True, exist_ok=True)
        accounting_file.write_text(content, encoding='utf-8')
        self.logger.info(f'Accounting sync created: {accounting_file.name}')
    
    def run(self):
        """Start the scheduler."""
        self.logger.info('Starting AIScheduler...')
        self.logger.info('Press Ctrl+C to stop')
        
        try:
            self.scheduler.start()
        except KeyboardInterrupt:
            self.logger.info('Scheduler stopped by user')
        except Exception as e:
            self.logger.error(f'Scheduler error: {e}', exc_info=True)
            raise


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: python scheduler.py <vault_path>")
        print("\nExample:")
        print("  python scheduler.py ../AI_Employee_Vault")
        sys.exit(1)
    
    vault_path = Path(sys.argv[1]).resolve()
    
    if not vault_path.exists():
        print(f"Error: Vault path does not exist: {vault_path}")
        sys.exit(1)
    
    scheduler = AIScheduler(str(vault_path))
    scheduler.run()


if __name__ == '__main__':
    main()
